/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fivekyu;

import org.junit.Test;
import static org.junit.Assert.*;

public class DoubleColaTest {

    @Test
    public void test1() {
        String[] names = new String[] { "Sheldon", "Leonard", "Penny", "Rajesh", "Howard" };
        int n = 1;
        assertEquals("Sheldon", new DoubleCola().whoIsNext(names, n));
    }

    @Test
    public void test2() {
        String[] names = new String[] { "Sheldon", "Leonard", "Penny", "Rajesh", "Howard" };
        int n = 6;
        assertEquals("Sheldon", new DoubleCola().whoIsNext(names, n));
    }
}
